import assets from "./assets";

const DocumentsData = [
  {
    folderId: "8b166f5d-7a19-4781-a898-3dd79826ed2d",
    folderSpecificName: "Test document",
    agreed: false,
    tab: "1",
    startPage: 1.0,
    globalPagePrefix: "R",
    duplicate: false,
    addedBy: { name: "frank brooks", teamName: "crunch", date: "2022-02-17T10:25:31.0062232Z" },
    bundleLocations: [
      {
        hasGlobalPaging: true,
        path: "r-esig",
        pathName: "R. esig",
        folderId: "8b166f5d-7a19-4781-a898-3dd79826ed2d",
        fileName: "Test document",
        containerType: "trialbook",
      },
    ],
    id: "TV-27-5782",
    sequence: 1,
    compositeKey: "TV-27-5782-1",
    type: "docx",
    name: "Test document",
    originalName: "Test document",
    pageCount: "1",
    source: "original",
    size: 11882,
    docDate: null,
    author: null,
    recipient: null,
    discoveryId: null,
    externalId: null,
    description: null,
    notes: null,
    createdBy: { name: "frank brooks", teamName: "crunch", date: "2022-02-17T10:20:59.4190807Z" },
    lastEditedBy: null,
    private: false,
    semiPrivate: false,
    hasAnnotations: true,
    hasPublicHyperlinks: true,
    assignedTo: ["trialbooks"],
    locations: ["R. esig"],
    highlights: null,
    attachments: [],
    tags: [
      {
        id: "8508c040-cde3-48fd-98df-c7a26f99b6a4",
        name: "test",
        color: "#000000",
        contextMenu: false,
        quickLinks: false,
      },
      {
        id: "89e63d8c-619c-4f52-a4fa-5649b6b26b2c",
        name: "lawyer",
        color: "#653294",
        contextMenu: true,
        quickLinks: true,
      },
    ],
    etag: '"ee01d1c7-0000-0c00-0000-621c96d10000"',
  },
  {
    folderId: "8b166f5d-7a19-4781-a898-3dd79826ed2d",
    folderSpecificName: null,
    agreed: false,
    tab: "2",
    startPage: 2.0,
    globalPagePrefix: "R",
    duplicate: false,
    addedBy: { name: "frank brooks", teamName: "crunch", date: "2022-02-17T10:28:53.3890248Z" },
    bundleLocations: [
      {
        hasGlobalPaging: true,
        path: "r-esig",
        pathName: "R. esig",
        folderId: "8b166f5d-7a19-4781-a898-3dd79826ed2d",
        fileName: "Brennan, Eric",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: true,
        path: "y-43-docs",
        pathName: "Y. 43 docs",
        folderId: "324ad078-e1de-4818-a1f6-b02529c113e2",
        fileName: "Brennan, Eric",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: true,
        path: "z-43-docs-w-subfolders/defendant-s-witness-statements-and-expert-reports",
        pathName: "Z. 43 DOCS W SUBFOLDERS > Defendant's Witness Statements and Expert Reports",
        folderId: "ff60e981-38f6-414a-9f5e-bac5ee4c0e8b",
        fileName: "Brennan, Eric",
        containerType: "trialbook",
      },
    ],
    id: "TV-27-1891",
    sequence: 2,
    compositeKey: "TV-27-1891-2",
    type: "pdf",
    name: "Brennan, Eric",
    originalName: "Brennan, Eric",
    pageCount: "1",
    source: "original",
    size: 32004,
    docDate: null,
    author: "test",
    recipient: "Vinay",
    discoveryId: null,
    externalId: null,
    description: null,
    notes: null,
    createdBy: { name: "frank brooks", teamName: "crunch", date: "2022-02-17T10:28:53.3890248Z" },
    lastEditedBy: { name: "Vinaysheel Wagh", teamName: "crunch", date: "2022-07-07T09:51:02.6911473Z" },
    private: false,
    semiPrivate: false,
    hasAnnotations: true,
    hasPublicHyperlinks: true,
    assignedTo: ["trialbooks"],
    locations: ["R. esig", "Y. 43 docs", "Defendant's Witness Statements and Expert Reports"],
    highlights: null,
    attachments: [],
    tags: [],
    etag: '"5d00c7c0-0000-0c00-0000-62c6ac860000"',
  },
  {
    folderId: "8b166f5d-7a19-4781-a898-3dd79826ed2d",
    folderSpecificName: null,
    agreed: false,
    tab: "3",
    startPage: 3.0,
    globalPagePrefix: "R",
    duplicate: false,
    addedBy: { name: "frank brooks", teamName: "crunch", date: "2022-02-17T10:28:53.5685685Z" },
    bundleLocations: [
      {
        hasGlobalPaging: true,
        path: "r-esig",
        pathName: "R. esig",
        folderId: "8b166f5d-7a19-4781-a898-3dd79826ed2d",
        fileName: "Coyle, Catiriona",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: true,
        path: "y-43-docs",
        pathName: "Y. 43 docs",
        folderId: "324ad078-e1de-4818-a1f6-b02529c113e2",
        fileName: "Coyle, Catiriona",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: true,
        path: "z-43-docs-w-subfolders/defendant-s-witness-statements-and-expert-reports",
        pathName: "Z. 43 DOCS W SUBFOLDERS > Defendant's Witness Statements and Expert Reports",
        folderId: "ff60e981-38f6-414a-9f5e-bac5ee4c0e8b",
        fileName: "Coyle, Catiriona up",
        containerType: "trialbook",
      },
    ],
    id: "TV-27-3303",
    sequence: 3,
    compositeKey: "TV-27-3303-3",
    type: "pdf",
    name: "Coyle, Catiriona",
    originalName: "Coyle, Catiriona",
    pageCount: "1",
    source: "original",
    size: 27422,
    docDate: null,
    author: null,
    recipient: null,
    discoveryId: null,
    externalId: null,
    description: null,
    notes: null,
    createdBy: { name: "frank brooks", teamName: "crunch", date: "2022-02-17T10:28:53.5685685Z" },
    lastEditedBy: null,
    private: true,
    semiPrivate: false,
    hasAnnotations: true,
    hasPublicHyperlinks: true,
    assignedTo: ["trialbooks"],
    locations: ["R. esig", "Y. 43 docs", "Defendant's Witness Statements and Expert Reports"],
    highlights: null,
    attachments: [],
    tags: [
      {
        id: "8508c040-cde3-48fd-98df-c7a26f99b6a4",
        name: "test",
        color: "#000000",
        contextMenu: true,
        quickLinks: false,
      },
    ],
    etag: '"110284dd-0000-0c00-0000-621cc1cf0000"',
  },
  {
    folderId: "8b166f5d-7a19-4781-a898-3dd79826ed2d",
    folderSpecificName: null,
    agreed: false,
    tab: "4",
    startPage: 4.0,
    globalPagePrefix: "R",
    duplicate: false,
    addedBy: { name: "frank brooks", teamName: "crunch", date: "2022-02-17T10:28:54.0548932Z" },
    bundleLocations: [
      {
        hasGlobalPaging: true,
        path: "r-esig",
        pathName: "R. esig",
        folderId: "8b166f5d-7a19-4781-a898-3dd79826ed2d",
        fileName: "Desrosiers, Hugo",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: true,
        path: "s-esig-2",
        pathName: "S. esig 2",
        folderId: "cc09877c-3275-4f7c-b424-fb7af112a742",
        fileName: "Desrosiers, Hugo direct",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: true,
        path: "y-43-docs",
        pathName: "Y. 43 docs",
        folderId: "324ad078-e1de-4818-a1f6-b02529c113e2",
        fileName: "Desrosiers, Hugo",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: true,
        path: "z-43-docs-w-subfolders/defendant-s-witness-statements-and-expert-reports",
        pathName: "Z. 43 DOCS W SUBFOLDERS > Defendant's Witness Statements and Expert Reports",
        folderId: "ff60e981-38f6-414a-9f5e-bac5ee4c0e8b",
        fileName: "Desrosiers, Hugo",
        containerType: "trialbook",
      },
    ],
    id: "TV-27-2003",
    sequence: 4,
    compositeKey: "TV-27-2003-4",
    type: "pdf",
    name: "Desrosiers, Hugo",
    originalName: "Desrosiers, Hugo",
    pageCount: "1",
    source: "original",
    size: 28580,
    docDate: "23/11/2021",
    author: null,
    recipient: null,
    discoveryId: null,
    externalId: null,
    description: null,
    notes: null,
    createdBy: { name: "frank brooks", teamName: "crunch", date: "2022-02-17T10:28:54.0548932Z" },
    lastEditedBy: { name: "Vinaysheel Wagh", teamName: "crunch", date: "2022-06-21T16:31:54.2252358Z" },
    private: true,
    semiPrivate: false,
    hasAnnotations: false,
    hasPublicHyperlinks: false,
    assignedTo: ["trialbooks"],
    locations: ["R. esig", "S. esig 2", "Y. 43 docs", "Defendant's Witness Statements and Expert Reports"],
    highlights: null,
    attachments: [],
    tags: [],
    etag: '"f301a156-0000-0c00-0000-62b1f27a0000"',
  },
  {
    folderId: "8b166f5d-7a19-4781-a898-3dd79826ed2d",
    folderSpecificName: null,
    agreed: false,
    tab: "5",
    startPage: 5.0,
    globalPagePrefix: "R",
    duplicate: false,
    addedBy: { name: "frank brooks", teamName: "crunch", date: "2022-02-17T12:02:40.4212874Z" },
    bundleLocations: [
      {
        hasGlobalPaging: true,
        path: "r-esig",
        pathName: "R. esig",
        folderId: "8b166f5d-7a19-4781-a898-3dd79826ed2d",
        fileName: "Coghlan, Paul",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: true,
        path: "y-43-docs",
        pathName: "Y. 43 docs",
        folderId: "324ad078-e1de-4818-a1f6-b02529c113e2",
        fileName: "Coghlan, Paul",
        containerType: "trialbook",
      },
    ],
    id: "TV-27-4112",
    sequence: 5,
    compositeKey: "TV-27-4112-5",
    type: "pdf",
    name: "Coghlan, Paul",
    originalName: "Coghlan, Paul",
    pageCount: "2",
    source: "original",
    size: 58673,
    docDate: null,
    author: null,
    recipient: null,
    discoveryId: null,
    externalId: null,
    description: null,
    notes: null,
    createdBy: { name: "frank brooks", teamName: "crunch", date: "2022-02-17T12:02:40.4212874Z" },
    lastEditedBy: null,
    private: true,
    semiPrivate: false,
    hasAnnotations: true,
    hasPublicHyperlinks: false,
    assignedTo: ["trialbooks"],
    locations: ["R. esig", "Y. 43 docs"],
    highlights: null,
    attachments: [],
    tags: [],
    etag: '"06007064-0000-0c00-0000-62274d880000"',
  },
  {
    folderId: "8b166f5d-7a19-4781-a898-3dd79826ed2d",
    folderSpecificName: null,
    agreed: false,
    tab: "6",
    startPage: 7.0,
    globalPagePrefix: "R",
    duplicate: false,
    addedBy: { name: "frank brooks", teamName: "crunch", date: "2022-02-17T12:03:07.5358346Z" },
    id: "TV-27-6274",
    sequence: 6,
    compositeKey: "TV-27-6274-6",
    type: "pdf",
    name: "Briggs, Anett",
    originalName: "Briggs, Anett",
    pageCount: "3",
    source: "original",
    size: 69313,
    docDate: "30/3/2022",
    author: null,
    recipient: null,
    discoveryId: null,
    externalId: null,
    description: null,
    notes: null,
    createdBy: { name: "frank brooks", teamName: "crunch", date: "2022-02-17T12:03:07.5358346Z" },
    lastEditedBy: { name: "Vinaysheel Wagh", teamName: "crunch", date: "2022-05-12T09:21:03.5524845Z" },
    private: false,
    semiPrivate: false,
    hasAnnotations: true,
    hasPublicHyperlinks: false,
    assignedTo: ["trialbooks"],
    locations: ["R. esig", "dayte sort", "Y. 43 docs", "Plaintiff's Witness Statements and Expert Reports"],
    highlights: null,
    attachments: [],
    tags: ["1"],
    etag: '"d8000b29-0000-0c00-0000-627cd17f0000"',
  },
  {
    folderId: "8b166f5d-7a19-4781-a898-3dd79826ed2d",
    folderSpecificName: "Galway City Council v Samuel Kingston",
    agreed: false,
    tab: "7",
    startPage: 10.0,
    globalPagePrefix: "R",
    duplicate: false,
    addedBy: { name: "frank brooks", teamName: "crunch", date: "2022-02-17T12:50:06.9734513Z" },
    id: "TV-27-0947",
    sequence: 7,
    compositeKey: "TV-27-0947-7",
    type: "pdf",
    name: "Galway City Council v Samuel Kingston",
    originalName: "Galway City Council v Samuel Kingston",
    pageCount: "4",
    source: "original",
    size: 302469,
    docDate: null,
    author: null,
    recipient: null,
    discoveryId: null,
    externalId: null,
    description: null,
    notes: null,
    createdBy: { name: "frank brooks", teamName: "crunch", date: "2021-11-10T17:00:53.4357763Z" },
    lastEditedBy: null,
    private: false,
    semiPrivate: false,
    hasAnnotations: false,
    hasPublicHyperlinks: false,
    assignedTo: ["trialbooks", "my-court-bundles", "team-bundles", "private-bundles"],
    locations: [
      "key correspondence",
      "defendant's witness statements up",
      "bundle c - 1 - 1 up",
      "Sort",
      "frank test",
      "S. esig 2",
      "T. xxx",
      "U. first time",
      "W. Please dont close trialbooks",
      "R. esig",
      "Y. 43 docs",
      "Defendant's Witness Statements and Expert Reports",
      "test",
      "test2",
    ],
    highlights: null,
    attachments: [],
    tags: [],
    etag: '"1d023209-0000-0c00-0000-62a09dad0000"',
  },
  {
    folderId: "8b166f5d-7a19-4781-a898-3dd79826ed2d",
    folderSpecificName: "Fourth Complaint",
    agreed: false,
    tab: "8",
    startPage: 14.0,
    globalPagePrefix: "R",
    duplicate: false,
    addedBy: { name: "Vinaysheel Wagh", teamName: "crunch", date: "2022-03-08T12:57:10.9062671Z" },
    id: "TV-27-0192",
    sequence: 8,
    compositeKey: "TV-27-0192-8",
    type: "pdf",
    name: "Fourth Complaint",
    originalName: "Fourth Complaint",
    pageCount: "2",
    source: "original",
    size: 101164,
    docDate: "20/7/2022",
    author: null,
    recipient: null,
    discoveryId: null,
    externalId: null,
    description: null,
    notes: null,
    createdBy: { name: "frank brooks", teamName: "crunch", date: "2021-11-10T16:59:54.8088207Z" },
    lastEditedBy: { name: "Vinaysheel Wagh", teamName: "crunch", date: "2022-07-08T08:42:42.2093258Z" },
    private: true,
    semiPrivate: false,
    hasAnnotations: true,
    hasPublicHyperlinks: true,
    assignedTo: ["trialbooks", "team-bundles"],
    locations: [
      "statements of case xy up",
      "bundle c 2",
      "bundle c 3",
      "court orders",
      "correspondence relating to norwich pharmacal order",
      "dayte sort",
      "Y. 43 docs",
      "Defendant's Witness Statements and Expert Reports",
      "R. esig",
      "team bundle",
      "Sorted",
      "started as private",
      "western1",
      "child 2",
    ],
    highlights: null,
    attachments: [],
    tags: ["1"],
    etag: '"e900b4c5-0000-0c00-0000-62d926150000"',
  },
  {
    folderId: "8b166f5d-7a19-4781-a898-3dd79826ed2d",
    folderSpecificName: null,
    agreed: false,
    tab: "9",
    startPage: 16.0,
    globalPagePrefix: "R",
    duplicate: false,
    addedBy: { name: "frank brooks", teamName: "Alt Team", date: "2022-03-25T15:35:37.7643461Z" },
    id: "TV-27-7341",
    sequence: 9,
    compositeKey: "TV-27-7341-9",
    type: "pdf",
    name: "JC04 STaylor Resignation 03-2019",
    originalName: "JC04 STaylor Resignation 03-2019",
    pageCount: "1",
    source: "original",
    size: 55269,
    docDate: null,
    author: null,
    recipient: null,
    discoveryId: null,
    externalId: null,
    description: null,
    notes: null,
    createdBy: { name: "frank brooks", teamName: "crunch", date: "2022-01-13T18:38:32.9132241Z" },
    lastEditedBy: null,
    private: true,
    semiPrivate: false,
    hasAnnotations: true,
    hasPublicHyperlinks: false,
    assignedTo: ["trialbooks"],
    locations: [
      "key correspondence",
      "correspondence relating to norwich pharmacal order",
      "Part B - Entry Applications",
      "Y. 43 docs",
      "Defendant's Witness Statements and Expert Reports",
      "Hyperlinks working well",
      "R. esig",
    ],
    highlights: null,
    attachments: [],
    tags: ["1"],
    etag: '"b102b8a7-0000-0c00-0000-623de1490000"',
  },
  {
    folderId: "8b166f5d-7a19-4781-a898-3dd79826ed2d",
    folderSpecificName: null,
    agreed: false,
    tab: "10",
    startPage: 17.0,
    globalPagePrefix: "R",
    duplicate: false,
    addedBy: { name: "frank brooks", teamName: "Alt Team", date: "2022-03-25T15:35:38.0013643Z" },
    id: "TV-27-2147",
    sequence: 10,
    compositeKey: "TV-27-2147-10",
    type: "pdf",
    name: "Prod0015291",
    originalName: "Prod0015291",
    pageCount: "1",
    source: "original",
    size: 193638,
    docDate: null,
    author: null,
    recipient: null,
    discoveryId: null,
    externalId: null,
    description: null,
    notes: null,
    createdBy: { name: "frank brooks", teamName: "Alt Team", date: "2022-03-25T10:08:39.8767132Z" },
    lastEditedBy: null,
    private: false,
    semiPrivate: false,
    hasAnnotations: false,
    hasPublicHyperlinks: false,
    assignedTo: ["trialbooks"],
    locations: ["D Murphy", "Hyperlinks working well", "R. esig"],
    highlights: null,
    attachments: [],
    tags: ["1"],
    etag: '"b102bca7-0000-0c00-0000-623de14a0000"',
  },
  {
    folderId: "8b166f5d-7a19-4781-a898-3dd79826ed2d",
    folderSpecificName: null,
    agreed: false,
    tab: "11",
    startPage: 18.0,
    globalPagePrefix: "R",
    duplicate: false,
    addedBy: { name: "frank brooks", teamName: "Alt Team", date: "2022-03-25T15:35:38.0735618Z" },
    bundleLocations: [
      {
        hasGlobalPaging: true,
        path: "r-esig",
        pathName: "R. esig",
        folderId: "8b166f5d-7a19-4781-a898-3dd79826ed2d",
        fileName: "Grounding Affidavit",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: false,
        path: "dayte-sort-up",
        pathName: "dayte sort up",
        folderId: "6d43a6f8-0e63-4cab-b731-44c8195c6c86",
        fileName: "Grounding Affidavit",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: false,
        path: "hyperlinks-working-well",
        pathName: "Hyperlinks working well",
        folderId: "fcdfa838-5004-440b-9922-9f064d2a2566",
        fileName: "Grounding Affidavit",
        containerType: "trialbook",
      },
    ],
    id: "TV-27-0188",
    sequence: 11,
    compositeKey: "TV-27-0188-11",
    type: "pdf",
    name: "Grounding Affidavit",
    originalName: "Grounding Affidavit",
    pageCount: "10",
    source: "original",
    size: 159995,
    docDate: null,
    author: null,
    recipient: null,
    discoveryId: null,
    externalId: null,
    description: null,
    notes: null,
    createdBy: { name: "frank brooks", teamName: "Alt Team", date: "2022-03-25T10:21:05.3594617Z" },
    lastEditedBy: null,
    private: false,
    semiPrivate: false,
    hasAnnotations: true,
    hasPublicHyperlinks: true,
    assignedTo: ["trialbooks"],
    locations: ["Hyperlinks working well", "dayte sort", "R. esig"],
    highlights: null,
    attachments: [],
    tags: [],
    etag: '"b102c1a7-0000-0c00-0000-623de14a0000"',
  },
  {
    folderId: "8b166f5d-7a19-4781-a898-3dd79826ed2d",
    folderSpecificName: "JC01 STaylor Contract2010",
    agreed: false,
    tab: "12",
    startPage: 28.0,
    globalPagePrefix: "R",
    duplicate: false,
    addedBy: { name: "frank brooks", teamName: "Alt Team", date: "2022-03-25T15:35:38.0159111Z" },
    bundleLocations: [
      {
        hasGlobalPaging: true,
        path: "bundle-b-orers-key-correspondence/disclosure",
        pathName: "Bundle B - Orers & Key Correspondence > disclosure",
        folderId: "a3a0869d-6bda-4b07-a4df-7124fffe16d1",
        fileName: "JC1 STaylor Contract2010",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: true,
        path: "bundle-d-inter-solicitor-correspondence/correspondence-relating-to-norwich-pharmacal-order",
        pathName: "bundle d inter solicitor correspondence > correspondence relating to norwich pharmacal order",
        folderId: "f4ffe838-887d-461e-b0da-959b631fa062",
        fileName: "JC01 STaylor Contract2010",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: true,
        path: "bundle-d-inter-solicitor-correspondence/key-correspondence-up",
        pathName: "bundle d inter solicitor correspondence > key correspondence up",
        folderId: "f3833218-31cc-451a-a042-a516e718ce38",
        fileName: "JC01 STaylor Contract2010",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: true,
        path: "r-esig",
        pathName: "R. esig",
        folderId: "8b166f5d-7a19-4781-a898-3dd79826ed2d",
        fileName: "JC01 STaylor Contract2010",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: true,
        path: "y-43-docs",
        pathName: "Y. 43 docs",
        folderId: "324ad078-e1de-4818-a1f6-b02529c113e2",
        fileName: "JC01 STaylor Contract2010",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: true,
        path: "z-43-docs-w-subfolders/defendant-s-witness-statements-and-expert-reports",
        pathName: "Z. 43 DOCS W SUBFOLDERS > Defendant's Witness Statements and Expert Reports",
        folderId: "ff60e981-38f6-414a-9f5e-bac5ee4c0e8b",
        fileName: "JC01 STaylor Contract2010",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: false,
        path: "dayte-sort-up",
        pathName: "dayte sort up",
        folderId: "6d43a6f8-0e63-4cab-b731-44c8195c6c86",
        fileName: "JC01 STaylor Contract2010",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: false,
        path: "hyperlinks-working-well",
        pathName: "Hyperlinks working well",
        folderId: "fcdfa838-5004-440b-9922-9f064d2a2566",
        fileName: "JC01 STaylor Contract2010",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: false,
        path: "rawlings/likeford-pleadings/part-b-entry-applications",
        pathName: "Rawlings > Likeford Pleadings > Part B - Entry Applications",
        folderId: "24bd159c-7c6c-4323-ba4f-c18d4723857f",
        fileName: "JC01 STaylor Contract2010",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: false,
        path: "team-bundle",
        pathName: "team bundle",
        folderId: "0a403a4c-8329-41cd-be56-cd4b9d3c68a4",
        fileName: "JC01 STaylor Contract2010",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: false,
        path: "started-as-private-up",
        pathName: "started as private up",
        folderId: "c523f4e1-edb6-483b-8750-e1b5705b66f8",
        fileName: "JC01 STaylor Contract2010",
        containerType: "team-bundle",
      },
      {
        hasGlobalPaging: false,
        path: "private-to-share-x",
        pathName: "Private To Share x",
        folderId: "e9a53d88-9a76-4271-845a-1e9e12142ac4",
        fileName: "JC01 STaylor Contract2010",
        containerType: "team-bundle",
      },
    ],
    id: "TV-27-8371",
    sequence: 12,
    compositeKey: "TV-27-8371-12",
    type: "pdf",
    name: "JC01 STaylor Contract2010",
    originalName: "JC01 STaylor Contract2010",
    pageCount: "4",
    source: "original",
    size: 181776,
    docDate: null,
    author: null,
    recipient: null,
    discoveryId: null,
    externalId: null,
    description: null,
    notes: null,
    createdBy: { name: "frank brooks", teamName: "crunch", date: "2022-01-13T18:02:25.0265464Z" },
    lastEditedBy: null,
    private: false,
    semiPrivate: false,
    hasAnnotations: false,
    hasPublicHyperlinks: true,
    assignedTo: ["trialbooks", "team-bundles"],
    locations: [
      "correspondence relating to norwich pharmacal order",
      "key correspondence",
      "Part B - Entry Applications",
      "Private To Share",
      "Y. 43 docs",
      "Defendant's Witness Statements and Expert Reports",
      "team bundle",
      "dayte sort",
      "started as private",
      "Hyperlinks working well",
      "R. esig",
      "disclosure",
    ],
    highlights: null,
    attachments: [],
    tags: [],
    etag: '"8e012575-0000-0c00-0000-62b058d10000"',
  },
  {
    folderId: "8b166f5d-7a19-4781-a898-3dd79826ed2d",
    folderSpecificName: null,
    agreed: false,
    tab: "13",
    startPage: 32.0,
    globalPagePrefix: "R",
    duplicate: false,
    addedBy: { name: "frank brooks", teamName: "Alt Team", date: "2022-03-25T15:35:38.1358184Z" },
    bundleLocations: [
      {
        hasGlobalPaging: true,
        path: "bundle-d-inter-solicitor-correspondence/correspondence-relating-to-norwich-pharmacal-order",
        pathName: "bundle d inter solicitor correspondence > correspondence relating to norwich pharmacal order",
        folderId: "f4ffe838-887d-461e-b0da-959b631fa062",
        fileName: "JC2 Ltr of Offer Feb14 Director CORE",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: true,
        path: "bundle-d-inter-solicitor-correspondence/key-correspondence-up",
        pathName: "bundle d inter solicitor correspondence > key correspondence up",
        folderId: "f3833218-31cc-451a-a042-a516e718ce38",
        fileName: "JC2 Ltr of Offer Feb14 Director CORE",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: true,
        path: "r-esig",
        pathName: "R. esig",
        folderId: "8b166f5d-7a19-4781-a898-3dd79826ed2d",
        fileName: "JC2 Ltr of Offer Feb14 Director CORE",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: true,
        path: "y-43-docs",
        pathName: "Y. 43 docs",
        folderId: "324ad078-e1de-4818-a1f6-b02529c113e2",
        fileName: "JC02 Ltr of Offer Feb14 Director CORE",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: true,
        path: "z-43-docs-w-subfolders/defendant-s-witness-statements-and-expert-reports",
        pathName: "Z. 43 DOCS W SUBFOLDERS > Defendant's Witness Statements and Expert Reports",
        folderId: "ff60e981-38f6-414a-9f5e-bac5ee4c0e8b",
        fileName: "JC02 Ltr of Offer Feb14 Director CORE",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: false,
        path: "hyperlinks-working-well",
        pathName: "Hyperlinks working well",
        folderId: "fcdfa838-5004-440b-9922-9f064d2a2566",
        fileName: "JC2 Ltr of Offer Feb14 Director CORE",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: false,
        path: "rawlings/likeford-pleadings/part-b-entry-applications",
        pathName: "Rawlings > Likeford Pleadings > Part B - Entry Applications",
        folderId: "24bd159c-7c6c-4323-ba4f-c18d4723857f",
        fileName: "JC2 Ltr of Offer Feb14 Director CORE",
        containerType: "trialbook",
      },
      {
        hasGlobalPaging: false,
        path: "private-to-share-x",
        pathName: "Private To Share x",
        folderId: "e9a53d88-9a76-4271-845a-1e9e12142ac4",
        fileName: "JC2 Ltr of Offer Feb14 Director CORE",
        containerType: "team-bundle",
      },
      {
        hasGlobalPaging: false,
        path: "test",
        pathName: "test",
        folderId: "ddbb09d6-44fc-45d1-a59e-143b82488567",
        fileName: "JC2 Ltr of Offer Feb14 Director CORE",
        containerType: "private-bundle",
      },
    ],
    id: "TV-27-4679",
    sequence: 13,
    compositeKey: "TV-27-4679-13",
    type: "pdf",
    name: "JC2 Ltr of Offer Feb14 Director CORE",
    originalName: "JC2 Ltr of Offer Feb14 Director CORE",
    pageCount: "3",
    source: "original",
    size: 223614,
    docDate: null,
    author: null,
    recipient: null,
    discoveryId: null,
    externalId: null,
    description: null,
    notes: null,
    createdBy: { name: "frank brooks", teamName: "crunch", date: "2022-01-13T18:38:17.8467557Z" },
    lastEditedBy: null,
    private: false,
    semiPrivate: false,
    hasAnnotations: false,
    hasPublicHyperlinks: false,
    assignedTo: ["trialbooks", "team-bundles", "private-bundles"],
    locations: [
      "key correspondence",
      "correspondence relating to norwich pharmacal order",
      "Part B - Entry Applications",
      "Private To Share",
      "Y. 43 docs",
      "Defendant's Witness Statements and Expert Reports",
      "Hyperlinks working well",
      "R. esig",
      "test",
    ],
    highlights: null,
    attachments: [],
    tags: [],
    etag: '"1c02e0e0-0000-0c00-0000-62a0992f0000"',
  },
  {
    folderId: "8b166f5d-7a19-4781-a898-3dd79826ed2d",
    folderSpecificName: null,
    agreed: false,
    tab: "14",
    startPage: 35.0,
    globalPagePrefix: "R",
    duplicate: false,
    addedBy: { name: "frank brooks", teamName: "Alt Team", date: "2022-03-25T15:35:38.2652549Z" },
    id: "TV-27-8639",
    sequence: 14,
    compositeKey: "TV-27-8639-14",
    type: "pdf",
    name: "Prod0015492",
    originalName: "Prod0015492",
    pageCount: "4",
    source: "original",
    size: 954132,
    docDate: null,
    author: null,
    recipient: null,
    discoveryId: null,
    externalId: null,
    description: null,
    notes: null,
    createdBy: { name: "frank brooks", teamName: "Alt Team", date: "2022-03-25T10:08:39.9482514Z" },
    lastEditedBy: null,
    private: true,
    semiPrivate: false,
    hasAnnotations: true,
    hasPublicHyperlinks: false,
    assignedTo: ["trialbooks"],
    locations: ["D Murphy", "R. esig"],
    highlights: null,
    attachments: [],
    tags: ["1"],
    etag: '"b102e3a7-0000-0c00-0000-623de14a0000"',
  },
  {
    folderId: "8b166f5d-7a19-4781-a898-3dd79826ed2d",
    folderSpecificName: null,
    agreed: false,
    tab: "15",
    startPage: 39.0,
    globalPagePrefix: "R",
    duplicate: false,
    addedBy: { name: "frank brooks", teamName: "Alt Team", date: "2022-03-25T15:35:38.7542612Z" },
    id: "TV-27-6878",
    sequence: 15,
    compositeKey: "TV-27-6878-15",
    type: "pdf",
    name: "JC03 STaylor Director Contract2014",
    originalName: "JC03 STaylor Director Contract2014",
    pageCount: "6",
    source: "original",
    size: 263182,
    docDate: null,
    author: null,
    recipient: null,
    discoveryId: null,
    externalId: null,
    description: null,
    notes: null,
    createdBy: { name: "frank brooks", teamName: "crunch", date: "2022-01-13T18:38:33.0950495Z" },
    lastEditedBy: null,
    private: false,
    semiPrivate: false,
    hasAnnotations: false,
    hasPublicHyperlinks: false,
    assignedTo: ["trialbooks", "team-bundles", "private-bundles"],
    locations: [
      "key correspondence",
      "correspondence relating to norwich pharmacal order",
      "Part B - Entry Applications",
      "Y. 43 docs",
      "Defendant's Witness Statements and Expert Reports",
      "Hyperlinks working well",
      "R. esig",
      "test",
      "test2",
    ],
    highlights: null,
    attachments: [],
    tags: [],
    etag: '"ea0086e8-0000-0c00-0000-62d92a390000"',
  },
];
export { DocumentsData };
